plugin/contents/ui/backend/Mpv.qml

As I think it truly works and what mpv option "panscan" is meaning [(mpv options)](https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst).

fix: fix display mode matching for mpv backend

---

plugin/contents/ui/WindowModel.qml

Should fix this bag #14
All these things only work if the correct geometry is set [(source)](https://github.com/KDE/plasma-workspace/blob/master/libtaskmanager/tasksmodel.h)
```
filterByActivity: true
filterByVirtualDesktop: true
filterByScreen: true
```
So wallpaper object doesn't has screenGeometry property. But it parent has this one.

fix: fix playback stop for multi monitor setups

---

CMakeLists.txt
README.md

A warning encountered by the new `cmake .. -DUSE_PLASMAPKG=ON` build method:
```
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
/usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
CMakeLists.txt:31 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
This seems benign so long as users have met the warning's minimum requirements. I don't know how FindKF5.cmake will react to a CMake version lower than 3.16. Simply keeping all packages up to date was sufficient for me. However, CMake 3.16+ should be added to the current requirements alongside QT 5.13+ and mpv to avoid confusion. …

CMake minimum version requirement

---

plugin/contents/ui/config.qml

This happened to me after updating:
I think it's the fault of my last commit - I didn't think that it wouldn't fit and disregarded width.
I added an implicitWidth to the TabBar to prevent it from happening again and it seems to work perfectly now. I am not sure if it was the fault of some other property in the code. If it is, feel free can change the width there - this is just a small fix because it annoyed me

Prevent overlapping text on the tab bar

---

README.md

Added `kf5-plasma-devel` as a necessary dependency to build on Fedora and cleaned up the text a little for Fedora and Debian dependencies to be a bit more consistent across all three distro sections.

README.md update: added Fedora dependency and cleaned up text a little

---

src/backend_scene/wallpaper/Utils/span.hpp

Fixes GCC 12 compilation
a208004af06ea696dcbb1aebc335e3276f2c72a8 seems to have caught another instance of something missing.

Add required library to #includes for GCC 12

---

plugin/contents/ui/config.qml
plugin/contents/ui/page/WallpaperPage.qml

Currently the color of some text in Config/Wallpaperpage doesn't use `Theme.textcolor`.
If the user uses white system theme, the original text can hardly be recognized.

fix: use theme color in config & wallpaperpage

---

src/backend_scene/third_party/vk_mem_alloc.h

The plugin wasn't building on openSUSE because it missed an include. This PR adds it.
Related to #286

Fix build on openSUSE TW(GCC 13 Distros)

---

src/backend_scene/src/WPSceneParser.cpp

Replaces `g_Color` with `g_Color4`, as suggested in #327. Seems to work fine on my end.
Suggestions welcome. (Some cleanup possibly?)

Adapt to Wallpaper Engine 2.3 color uniform name

---

plugin/contents/config/main.xml
plugin/contents/ui/PowerSource.qml
plugin/contents/ui/config.qml
plugin/contents/ui/main.qml
plugin/contents/ui/page/SettingPage.qml

AC adapter may be plugged in while its power is not enough to charge the battery. A better option is to pause when battery is discharging.

Pause when PC is on battery power

---

src/backend_scene/src/WPSceneParser.cpp

The opacity/alpha property isn't passed to shader correctly, causing some scene not rendering correctly,
e.g. [Starry Sky (2593802083)](https://steamcommunity.com/sharedfiles/filedetails/?id=2593802083)
Closes: #342
Fixes: c00b244 ("add alpha to color4")
Related: #327 #331
Maybe need more testing to see if this breaks other scenes.

Add image alpha to `g_Color4`

---

README.md

Dependency needed for cmake to compile properly in OpenSUSE. This fixes #160.

Add extra-cmake-modules dependency (Fix #160)

---

plugin/contents/ui/Pyext.qml

When using
```sh
cmake --build build --target install_pkg
```
It install into $HOME/.local/share/plasma/wallpapers/com.github.catsout.WallpaperEngineKde/
But in [Pyext.qml](https://github.com/catsout/wallpaper-engine-kde-plugin/blob/qt6/plugin/contents/ui/Pyext.qml) it's trying to execute [pyext.py](https://github.com/catsout/wallpaper-engine-kde-plugin/blob/qt6/plugin/contents/pyext.py) with
"plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py".
So the path doesn't match. Causing a no such file or directory error with python.

Fixed a typo causing python unable to find execute pyext.py

---

CMakeLists.txt

ID mismatch then Plasma doesn't recognize this wallpaper.
Fixes: 98bf9ff ("update install readme")

Fix install when not using kpackagetool6

---

plugin/contents/ui/WindowModel.qml
plugin/contents/ui/main.qml

In Plasma 6, the activity of wallpaper seems not accessible by `wallpaper.parent.activity`, then auto pause with maximized/focused window fails because it filters window with activity id.
This patch fixes auto pause by setting `wModel.activity`, using same method as `wModel.desktop`.
Please check whether this can fix auto pause in your environment @AngelSherry  @zjypls

Fix auto pause in WindowModel

---

plugin/contents/ui/backend/Scene.qml
plugin/contents/ui/main.qml
src/MouseGrabber.cpp
src/MouseGrabber.hpp

Hello! After some testing I managed to find and fix the issue with mouse hover on the QT6 branch using Plasma 6.
System Specs:
- Plasma 6.0.5
- QMake version 3.1
- Using Qt version 6.7.1
The main problem was that `this.mouseInput` was being used instead of `background.mouseInput`, causing the `Timer` to always return without grabbing the mouse correctly.
Other changes I made:
* Added includes to MouseGrabber and simplified some logic
* Changed a Scene.qml `Connection` that was using deprecated syntax
* Forced `override` in all MouseGrabber functions. I'm not sure if it's needed since it was added before I detected the problem with `this.mouseInput`

Fix Mouse Hover on Scene Wallpapers

---

plugin/contents/ui/main.qml
src/CMakeLists.txt
src/TTYSwitchMonitor.cpp
src/TTYSwitchMonitor.hpp
src/plugin.cpp

Fix for #415
Detect when the user is switching TTY and pause wallpapers. Detect when the user returns and unpause.

Fix for #415 prevent crash when switching to TTY and back

---

plugin/contents/ui/Common.qml
plugin/contents/ui/WallpaperListModel.qml
plugin/contents/ui/config.qml
plugin/contents/ui/main.qml
plugin/contents/ui/page/WallpaperPage.qml

Fixes #128
Combined with the ability to randomly cycle through the currently filtered wallpaper list, this should give the ability to cycle through wallpapers like in the Windows app.
This also means you can cycle through the union of two or more playlists or some other combination of playlists and other filters, which is a pretty cool enhancement on the Windows app's capabilities.
Needed to shore up some of the async code as part of the solution to a race condition when configuring multiple displays to shuffle the filter simultaneously.

Added playlists as a filterable property. Should solve #128

---

README.md

Merged edit of `git clone` instruction from qt6 will no longer work, since that branch got deleted after. This PR removes selection of qt6 branch in the clone instructions.
Also I think that `support kde6` maybe should be removed from [Todo section](https://github.com/catsout/wallpaper-engine-kde-plugin?tab=readme-ov-file#todo), but that's out of the scope of this PR that just fixes a non working `git clone` command (I can amend it to this one if you want to)

Remove qt6 branch selection

---

README.md

Still does not fully compile on Fedora Linux 40, but a step closer. 
Added additional dependency libplasma-devel to the Fedora dependency installation section.

Updated Fedora Section of Read Me 

---

README.md

This adds ninja to the pacman command for setup, which is required to perform the build instructions. This addresses issue #434 for Arch (SteamDeck will require some investigation, which I can try later. Someone with more Fedora experience can validate the ninja-build requirement).

Updated Arch section of README.md
